apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multitracker-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
    - hosts:
        - multitracker.app.flg.domo
      secretName: star-app-tls
  rules:
    - host: multitracker.app.flg.domo
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: multitracker
                port:
                  number: 443